platform :ios, '8.0'

target 'ARORequestSample' do
  use_frameworks!

  pod 'ARORequest', path: '../'
  pod 'RxSwift', git: 'https://github.com/ReactiveX/RxSwift.git', branch: 'rxswift4.0-swift4.0'
end
